-- AlterTable
ALTER TABLE `log_transacao` ADD COLUMN `DATA_TRANSACAO` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    ADD COLUMN `VALOR` DECIMAL(12, 2) NOT NULL DEFAULT 0.00;

-- CreateIndex
CREATE INDEX `IX_LOG_STATUS` ON `log_transacao`(`STATUS`);

-- CreateIndex
CREATE INDEX `IX_LOG_DATA_TRANSACAO` ON `log_transacao`(`DATA_TRANSACAO`);

-- CreateIndex
CREATE INDEX `IX_LOG_STATUS_DATA` ON `log_transacao`(`STATUS`, `DATA_TRANSACAO`);
