-- AlterTable
ALTER TABLE `plano` ADD COLUMN `PRIORIDADE` INTEGER UNSIGNED NOT NULL DEFAULT 3;

-- AlterTable
ALTER TABLE `solicitacao_analise` ADD COLUMN `PRIORIDADE` INTEGER UNSIGNED NOT NULL DEFAULT 3;

-- CreateIndex
CREATE INDEX `IX_PLANO_PRIORIDADE` ON `plano`(`PRIORIDADE`);

-- CreateIndex
CREATE INDEX `IX_SA_PRIORIDADE_STATUS` ON `solicitacao_analise`(`PRIORIDADE`, `STATUS`);
