-- CreateTable
CREATE TABLE `solicitacao_reembolso_credito` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `ID_COMPRA` INTEGER UNSIGNED NOT NULL,
    `ID_CLIENTE` INTEGER UNSIGNED NOT NULL,
    `STATUS` VARCHAR(50) NOT NULL DEFAULT 'PENDENTE',
    `MOTIVO` TEXT NULL,
    `QUANTIDADE` INTEGER UNSIGNED NOT NULL,
    `VALOR` DECIMAL(12, 2) NOT NULL,
    `DATA_CRIACAO` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `DATA_ATUALIZACAO` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `IX_SOL_REEMB_CLIENTE`(`ID_CLIENTE`),
    INDEX `IX_SOL_REEMB_STATUS`(`STATUS`),
    UNIQUE INDEX `UK_SOL_REEMB_COMPRA`(`ID_COMPRA`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `solicitacao_reembolso_credito` ADD CONSTRAINT `FK_SOL_REEMB_COMPRA` FOREIGN KEY (`ID_COMPRA`) REFERENCES `compra_credito`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `solicitacao_reembolso_credito` ADD CONSTRAINT `FK_SOL_REEMB_CLIENTE` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
