-- AlterTable
ALTER TABLE `cliente` ADD COLUMN `DATA_CRIACAO` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `plano` ADD COLUMN `VALOR_MENSAL` DECIMAL(10, 2) NOT NULL DEFAULT 0.00;

-- AlterTable
ALTER TABLE `solicitacao_analise` ADD COLUMN `DATA_SOLICITACAO` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- CreateIndex
CREATE INDEX `IX_CLIENTE_DATA_CRIACAO` ON `cliente`(`DATA_CRIACAO`);

-- CreateIndex
CREATE INDEX `IX_SA_DATA_SOLICITACAO` ON `solicitacao_analise`(`DATA_SOLICITACAO`);
