-- CreateTable
CREATE TABLE `assinatura_fatura` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `ID_ASSINATURA` INTEGER UNSIGNED NOT NULL,
    `STRIPE_INVOICE_ID` VARCHAR(255) NOT NULL,
    `STATUS` VARCHAR(50) NOT NULL,
    `VALOR` DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    `CREDITOS_CONCEDIDOS` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `PERIODO_INICIO` DATETIME(0) NULL,
    `PERIODO_FIM` DATETIME(0) NULL,
    `DATA_CRIACAO` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `UK_ASSIN_FATURA_STRIPE_INVOICE`(`STRIPE_INVOICE_ID`),
    INDEX `IX_ASSIN_FATURA_ID_ASSIN`(`ID_ASSINATURA`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `assinatura_fatura` ADD CONSTRAINT `FK_ASSIN_FATURA_ASSIN` FOREIGN KEY (`ID_ASSINATURA`) REFERENCES `assinatura`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
