-- CreateTable
CREATE TABLE `reembolso_credito` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `ID_COMPRA` INTEGER UNSIGNED NOT NULL,
    `STRIPE_REFUND_ID` VARCHAR(255) NOT NULL,
    `QUANTIDADE` INTEGER UNSIGNED NOT NULL,
    `VALOR` DECIMAL(12, 2) NOT NULL,
    `STATUS` VARCHAR(50) NOT NULL,
    `DATA_CRIACAO` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `DATA_ATUALIZACAO` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `reembolso_credito_STRIPE_REFUND_ID_key`(`STRIPE_REFUND_ID`),
    INDEX `reembolso_credito_ID_COMPRA_idx`(`ID_COMPRA`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `reembolso_credito` ADD CONSTRAINT `reembolso_credito_ID_COMPRA_fkey` FOREIGN KEY (`ID_COMPRA`) REFERENCES `compra_credito`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
