-- CreateTable
CREATE TABLE `compra_credito` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `ID_CLIENTE` INTEGER UNSIGNED NOT NULL,
    `QUANTIDADE` INTEGER UNSIGNED NOT NULL,
    `VALOR_UNITARIO` DECIMAL(10, 2) NOT NULL,
    `VALOR_TOTAL` DECIMAL(12, 2) NOT NULL,
    `STATUS` VARCHAR(50) NOT NULL,
    `STRIPE_SESSION_ID` VARCHAR(255) NOT NULL,
    `DATA_CRIACAO` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `DATA_PAGAMENTO` DATETIME(0) NULL,

    UNIQUE INDEX `UK_COMPRA_CRED_STRIPE_SESSION`(`STRIPE_SESSION_ID`),
    INDEX `IX_COMPRA_CRED_CLIENTE`(`ID_CLIENTE`),
    INDEX `IX_COMPRA_CRED_STATUS`(`STATUS`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `compra_credito` ADD CONSTRAINT `FK_COMPRA_CRED_CLIENTE` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
