-- CreateTable
CREATE TABLE `solicitacao_reembolso_assinatura` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `ID_ASSINATURA` INTEGER UNSIGNED NOT NULL,
    `ID_CLIENTE` INTEGER UNSIGNED NOT NULL,
    `STRIPE_INVOICE_ID` VARCHAR(255) NOT NULL,
    `STATUS` VARCHAR(50) NOT NULL DEFAULT 'PENDENTE',
    `MOTIVO` TEXT NULL,
    `VALOR` DECIMAL(12, 2) NOT NULL,
    `CREDITOS` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `DATA_CRIACAO` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `DATA_ATUALIZACAO` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `UK_SOL_REEMB_ASSIN_INVOICE`(`STRIPE_INVOICE_ID`),
    INDEX `IX_SOL_REEMB_ASSIN_CLIENTE`(`ID_CLIENTE`),
    INDEX `IX_SOL_REEMB_ASSIN_STATUS`(`STATUS`),
    INDEX `IX_SOL_REEMB_ASSIN_ASSIN`(`ID_ASSINATURA`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `reembolso_assinatura` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `ID_SOLICITACAO` INTEGER UNSIGNED NOT NULL,
    `STRIPE_REFUND_ID` VARCHAR(255) NOT NULL,
    `STATUS` VARCHAR(50) NOT NULL,
    `VALOR` DECIMAL(12, 2) NOT NULL,
    `DATA_CRIACAO` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `DATA_ATUALIZACAO` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `UK_REEMB_ASSIN_SOL`(`ID_SOLICITACAO`),
    UNIQUE INDEX `UK_REEMB_ASSIN_STRIPE_REFUND`(`STRIPE_REFUND_ID`),
    INDEX `IX_REEMB_ASSIN_SOL`(`ID_SOLICITACAO`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `solicitacao_reembolso_assinatura` ADD CONSTRAINT `FK_SOL_REEMB_ASSIN_ASSIN` FOREIGN KEY (`ID_ASSINATURA`) REFERENCES `assinatura`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `solicitacao_reembolso_assinatura` ADD CONSTRAINT `FK_SOL_REEMB_ASSIN_CLIENTE` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `reembolso_assinatura` ADD CONSTRAINT `FK_REEMB_ASSIN_SOL` FOREIGN KEY (`ID_SOLICITACAO`) REFERENCES `solicitacao_reembolso_assinatura`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
