-- CreateTable
CREATE TABLE `admin` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `EMAIL` VARCHAR(255) NOT NULL,
    `SENHA` VARCHAR(255) NOT NULL,

    UNIQUE INDEX `UK_ADMIN_EMAIL`(`EMAIL`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `assinatura` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `ID_PLANO` INTEGER UNSIGNED NOT NULL,
    `NOME` VARCHAR(255) NOT NULL,
    `DATA_ASSINATURA` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `STATUS` VARCHAR(50) NOT NULL,
    `ID_CLIENTE_ADMIN_DA_ASSINATURA` INTEGER UNSIGNED NOT NULL,
    `ID_VINCULO_STRIPE` VARCHAR(255) NULL,

    UNIQUE INDEX `UK_ASSINATURA_VINCULO_STRIPE`(`ID_VINCULO_STRIPE`),
    INDEX `IX_ASSINATURA_ID_CLIENTE_ADMIN`(`ID_CLIENTE_ADMIN_DA_ASSINATURA`),
    INDEX `IX_ASSINATURA_ID_PLANO`(`ID_PLANO`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `cliente` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `EMAIL` VARCHAR(255) NOT NULL,
    `NOME` VARCHAR(255) NOT NULL,
    `SALDO` DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    `ID_ASSINATURA` INTEGER UNSIGNED NULL,
    `ID_EMPRESA` INTEGER UNSIGNED NULL,
    `COMPRA_NO_SISTEMA` BOOLEAN NOT NULL DEFAULT false,

    UNIQUE INDEX `UK_CLIENTE_EMAIL`(`EMAIL`),
    INDEX `IX_CLIENTE_ID_ASSINATURA`(`ID_ASSINATURA`),
    INDEX `IX_CLIENTE_ID_EMPRESA`(`ID_EMPRESA`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `empresa` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `CNPJ` VARCHAR(18) NOT NULL,
    `NOME` VARCHAR(255) NOT NULL,
    `IMAGEM_DA_LOGO` VARCHAR(500) NULL,

    UNIQUE INDEX `UK_EMPRESA_CNPJ`(`CNPJ`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `log_transacao` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `TIPO` ENUM('ASSINATURA', 'COMPRA_AVULSA') NOT NULL,
    `ID_CLIENTE` INTEGER UNSIGNED NOT NULL,
    `STATUS` VARCHAR(50) NOT NULL,

    INDEX `IX_LOG_ID_CLIENTE`(`ID_CLIENTE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `plano` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(255) NOT NULL,
    `QUANT_CREDITO_MENSAL` INTEGER UNSIGNED NOT NULL,
    `ID_STRIPE` VARCHAR(255) NOT NULL,

    UNIQUE INDEX `UK_PLANO_ID_STRIPE`(`ID_STRIPE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `preco_credito` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `VALOR` DECIMAL(10, 2) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `produto` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(255) NOT NULL,
    `TIPO` ENUM('BIOLÓGICO', 'QUÍMICO') NOT NULL,
    `E_PARA_DEMO` BOOLEAN NOT NULL DEFAULT false,

    INDEX `IX_PRODUTO_TIPO`(`TIPO`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `resultado_catalogado` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `ID_PRODUTO_QUIMICO` INTEGER UNSIGNED NULL,
    `ID_PRODUTO_BIOLOGICO` INTEGER UNSIGNED NULL,
    `STATUS` VARCHAR(50) NOT NULL,
    `DESCRICAO` TEXT NULL,

    INDEX `IX_RC_ID_PROD_BIOLOGICO`(`ID_PRODUTO_BIOLOGICO`),
    INDEX `IX_RC_ID_PROD_QUIMICO`(`ID_PRODUTO_QUIMICO`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `solicitacao_adicao_produto` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `TIPO` ENUM('BIOLÓGICO', 'QUÍMICO') NOT NULL,
    `NOME` VARCHAR(255) NOT NULL,
    `ID_CLIENTE` INTEGER UNSIGNED NOT NULL,
    `ID_ADMIN_QUE_RESPONDEU_A_SOLICITACAO` INTEGER UNSIGNED NULL,

    INDEX `IX_SAP_ID_ADMIN`(`ID_ADMIN_QUE_RESPONDEU_A_SOLICITACAO`),
    INDEX `IX_SAP_ID_CLIENTE`(`ID_CLIENTE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `solicitacao_analise` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `ID_PRODUTO_QUIMICO` INTEGER UNSIGNED NULL,
    `ID_PRODUTO_BIOLOGICO` INTEGER UNSIGNED NULL,
    `ID_CLIENTE` INTEGER UNSIGNED NOT NULL,
    `ID_ADMIN_QUE_RESPONDEU_A_SOLICITACAO` INTEGER UNSIGNED NULL,
    `DATA_RESPOSTA` DATETIME(0) NULL,
    `STATUS` VARCHAR(50) NOT NULL,
    `DESCRICAO` TEXT NULL,

    INDEX `IX_SA_ID_ADMIN`(`ID_ADMIN_QUE_RESPONDEU_A_SOLICITACAO`),
    INDEX `IX_SA_ID_CLIENTE`(`ID_CLIENTE`),
    INDEX `IX_SA_ID_PROD_BIOLOGICO`(`ID_PRODUTO_BIOLOGICO`),
    INDEX `IX_SA_ID_PROD_QUIMICO`(`ID_PRODUTO_QUIMICO`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `assinatura` ADD CONSTRAINT `FK_ASSINATURA_CLIENTE_ADMIN` FOREIGN KEY (`ID_CLIENTE_ADMIN_DA_ASSINATURA`) REFERENCES `cliente`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `assinatura` ADD CONSTRAINT `FK_ASSINATURA_PLANO` FOREIGN KEY (`ID_PLANO`) REFERENCES `plano`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `cliente` ADD CONSTRAINT `FK_CLIENTE_ASSINATURA` FOREIGN KEY (`ID_ASSINATURA`) REFERENCES `assinatura`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `cliente` ADD CONSTRAINT `FK_CLIENTE_EMPRESA` FOREIGN KEY (`ID_EMPRESA`) REFERENCES `empresa`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `log_transacao` ADD CONSTRAINT `FK_LOG_CLIENTE` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `resultado_catalogado` ADD CONSTRAINT `FK_RC_PROD_BIOLOGICO` FOREIGN KEY (`ID_PRODUTO_BIOLOGICO`) REFERENCES `produto`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `resultado_catalogado` ADD CONSTRAINT `FK_RC_PROD_QUIMICO` FOREIGN KEY (`ID_PRODUTO_QUIMICO`) REFERENCES `produto`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `solicitacao_adicao_produto` ADD CONSTRAINT `FK_SAP_ADMIN` FOREIGN KEY (`ID_ADMIN_QUE_RESPONDEU_A_SOLICITACAO`) REFERENCES `admin`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `solicitacao_adicao_produto` ADD CONSTRAINT `FK_SAP_CLIENTE` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `solicitacao_analise` ADD CONSTRAINT `FK_SA_ADMIN` FOREIGN KEY (`ID_ADMIN_QUE_RESPONDEU_A_SOLICITACAO`) REFERENCES `admin`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `solicitacao_analise` ADD CONSTRAINT `FK_SA_CLIENTE` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `solicitacao_analise` ADD CONSTRAINT `FK_SA_PROD_BIOLOGICO` FOREIGN KEY (`ID_PRODUTO_BIOLOGICO`) REFERENCES `produto`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `solicitacao_analise` ADD CONSTRAINT `FK_SA_PROD_QUIMICO` FOREIGN KEY (`ID_PRODUTO_QUIMICO`) REFERENCES `produto`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;
